name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build container
      run: docker-compose build
      
    - name: Start container
      run: docker-compose run -d --service-ports ElCamelloAPI

    - name: Stop containers
      if: always()
      run: docker-compose down
